# Generated by Django 5.1.7 on 2025-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_brand_category_product_productimage_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, max_length=155, related_name='products', to='shop.brand'),
        ),
    ]
