# Generated by Django 5.1.7 on 2025-03-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_image_productimage_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CarousalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='carousal_images/')),
                ('carousal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.carousal')),
            ],
        ),
    ]
