# Generated by Django 5.1.7 on 2025-03-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_favoriteproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='category_images/')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.category')),
            ],
        ),
    ]
