# Generated by Django 5.1.7 on 2025-03-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='images',
            new_name='image',
        ),
    ]
